# Spring application properties
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bisket?useSSL=false&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true&sessionVariables=wait_timeout=600&serverTimezone=Asia/Seoul"
    username: ""
    password: ""
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

# API server properties
server:
  port: 8080
  servlet:
    context-path: /v1

#Logger properties
logging:
  level:
    org.hibernate.SQL: debug
